{
	"whitelist": [
		".tw-icon, .ig-comments-icon",
		".tw-example #tw-wrap, .tw-example #instructions",
		".ig-likes:before",
		".ig-likes, .ig-comments",
		".opened #wrapper,",
		".closed #leavebehind",
		".ig-stats",
		".ut-feed-inner",
		"#generic_data .ut-feed-item-inner",
		".ut-feed-item-username",
		".ut-feed-item-name",
		".ut-feed-item-content",
		".ut-feed-controls",
		".ut-feed-control",
		".ut-feed-up:before",
		".ut-feed-down:before",
		".ig-content > img",
		".ut-feed-wrapper-twitter",
		".tw-tweet",
		".tw-header",
		".tw-permalink",
		".tw-avatar",
		".tw-content",
		".tw-full-name",
		".tw-nickname",
		".tw-retweet-credit",
		".tw-action .tw-icon",
		".ig-timestamp",
		".tw-icon-retweet",
		".tw-icon-reply",
		".tw-footer",
		".tw-tweet:hover .tw-footer,",
		".fpf .tw-footer",
		".tw-footer .tw-icon-retweet",
		".tw-icon-fav",
		".tw-icon-reply:hover, .tw-footer .tw-icon-retweet:hover, .tw-icon-fav:hover",
		".tw-permalink:hover, .tw-header:hover .tw-full-name, .tw-content [data-uthref]:hover",
		".tw-icon.clicked,",
		".tw-icon.clicked:hover",
		".tw-icon-retweet.clicked,",
		".tw-icon-retweet.clicked:hover",
		".ig-timestamp, .ig-avatar",
		"#ig-wrap",
		".ut-feed-wrapper-instagram",
		".ig-wrapper",
		".ig-gram",
		".ig-avatar",
		".ig-header",
		".ig-header:before",
		".ig-username",
		".ig-comments .ig-comments-icon"
	]
}