{
	"whitelist": [
		".leaflet-oldie",
		".leaflet-map-pane",
		".leaflet-tile",
		".leaflet-tile-loaded",
		".leaflet-marker-icon",
		".leaflet-marker-shadow",
		".leaflet-tile-pane",
		".leaflet-tile-container",
		".leaflet-overlay-pane",
		".leaflet-shadow-pane",
		".leaflet-marker-pane",
		".leaflet-popup-pane",
		".leaflet-objects-pane",
		".leaflet-overlay-pane",
		".leaflet-vml-shape",
		".lvml",
		".leaflet-zoom-box",
		".leaflet-image-layer",
		".leaflet-layer",
		".leaflet-tile",
		".leaflet-marker-icon",
		".leaflet-marker-shadow",
		".leaflet-marker-icon",
		".leaflet-marker-shadow",
		".leaflet-control-zoom",
		".marker-cluster-small",
		".placeholder",
		".leaflet-container",
		".leaflet-control",
		".leaflet-bottom",
		".leaflet-top",
		".leaflet-right",
		".leaflet-div-icon",
		".leaflet-fade-anim",
		".leaflet-popup",
		".leaflet-zoom-anim",
		".leaflet-touching",
		".leaflet-zoom-hide",
		".leaflet-clickable",
		".leaflet-active",
		".leaflet-control-zoom-in",
		".leaflet-touch",
		".leaflet-control-zoom-in",
		".leaflet-control-zoom-out",
		".leaflet-control-layers",
		".leaflet-control-layers-toggle",
		".leaflet-retina",
		".leaflet-control-layers-expanded",
		".leaflet-control-layers-list",
		".leaflet-control-layers-selector",
		".leaflet-control-layers-separator",
		".leaflet-control-attribution",
		".leaflet-control-scale-line",
		".leaflet-popup-content-wrapper",
		".leaflet-popup-content",
		".leaflet-popup-tip-container",
		".leaflet-popup-scrolled",
		".marker-cluster-medium",
		".marker-cluster-large",
		".drawer",
		".drawer-inner",
		".show-drawer",
		".drawer-open",
		".drawer-buttons",
		".drawer-name",
		".map-search-error",
		".leaflet-control-geosearch",
		".leaflet-control-geosearch-wrap",
		".animate-spin",
		".icon-spin-inner",
		".leaflet-bar-part-single",
		".leaflet-control-locate",
		".leaflet-oldie .marker-cluster-large",
		".leaflet-marker-icon,.leaflet-marker-shadow,.leaflet-tile",
		".leaflet-container img",
		".leaflet-container img.leaflet-image-layer",
		".leaflet-overlay-pane svg",
		".leaflet-bottom,.leaflet-top",
		".leaflet-left",
		".leaflet-right .leaflet-control",
		".leaflet-top .leaflet-control",
		".leaflet-bottom .leaflet-control",
		".leaflet-left .leaflet-control",
		".leaflet-fade-anim .leaflet-popup,.leaflet-fade-anim .leaflet-tile",
		".leaflet-fade-anim .leaflet-map-pane .leaflet-popup,.leaflet-fade-anim .leaflet-tile-loaded",
		".leaflet-zoom-anim .leaflet-zoom-animated",
		".leaflet-pan-anim .leaflet-tile,.leaflet-touching .leaflet-zoom-animated,.leaflet-zoom-anim .leaflet-tile",
		".leaflet-zoom-anim .leaflet-zoom-hide",
		".leaflet-control,.leaflet-popup-pane",
		".leaflet-dragging .leaflet-clickable,.leaflet-dragging .leaflet-container",
		".leaflet-container a",
		".leaflet-container a.leaflet-active",
		".leaflet-bar",
		".leaflet-bar a,.leaflet-bar a:hover",
		".leaflet-bar a,.leaflet-control-layers-toggle",
		".leaflet-bar a:hover",
		".leaflet-bar a:first-child",
		".leaflet-bar a:last-child",
		".leaflet-bar a.leaflet-disabled",
		".leaflet-touch .leaflet-bar a",
		".leaflet-control-zoom-in,.leaflet-control-zoom-out",
		".leaflet-touch .leaflet-control-zoom-in",
		".leaflet-touch .leaflet-control-zoom-out",
		".leaflet-retina .leaflet-control-layers-toggle",
		".leaflet-touch .leaflet-control-layers-toggle",
		".leaflet-control-layers .leaflet-control-layers-list,.leaflet-control-layers-expanded .leaflet-control-layers-toggle",
		".leaflet-control-layers-expanded .leaflet-control-layers-list",
		".leaflet-control-layers label",
		".leaflet-container .leaflet-control-attribution",
		".leaflet-control-attribution,.leaflet-control-scale-line",
		".leaflet-control-attribution a",
		".leaflet-control-attribution a:hover",
		".leaflet-container .leaflet-control-attribution,.leaflet-container .leaflet-control-scale",
		".leaflet-left .leaflet-control-scale",
		".leaflet-bottom .leaflet-control-scale",
		".leaflet-control-scale-line:not(:first-child)",
		".leaflet-control-scale-line:not(:first-child):not(:last-child)",
		".leaflet-touch .leaflet-bar,.leaflet-touch .leaflet-control-attribution,.leaflet-touch .leaflet-control-layers",
		".leaflet-touch .leaflet-bar,.leaflet-touch .leaflet-control-layers",
		".leaflet-popup-content p",
		".leaflet-popup-tip",
		".leaflet-popup-content-wrapper,.leaflet-popup-tip",
		".leaflet-container a.leaflet-popup-close-button",
		".leaflet-container a.leaflet-popup-close-button:hover",
		".leaflet-oldie .leaflet-popup-content-wrapper",
		".leaflet-oldie .leaflet-popup-tip",
		".leaflet-oldie .leaflet-popup-tip-container",
		".leaflet-oldie .leaflet-control-layers,.leaflet-oldie .leaflet-control-zoom,.leaflet-oldie .leaflet-popup-content-wrapper,.leaflet-oldie .leaflet-popup-tip",
		".leaflet-cluster-anim .leaflet-marker-icon,.leaflet-cluster-anim .leaflet-marker-shadow",
		".marker-cluster-small div",
		".marker-cluster-medium div",
		".marker-cluster-large div",
		".leaflet-oldie .marker-cluster-small",
		".leaflet-oldie .marker-cluster-small div",
		".leaflet-oldie .marker-cluster-medium",
		".leaflet-oldie .marker-cluster-medium div",
		".leaflet-marker-icon,.leaflet-marker-shadow",
		".leaflet-oldie .marker-cluster-large div",
		".marker-cluster",
		".marker-cluster div",
		".marker-cluster span",
		".leaflet-container *,.leaflet-container :after,.leaflet-container :before",
		".leaflet-control-geosearch-icon",
		".leaflet-control-geosearch-icon a",
		".leaflet-control-geosearch-icon img",
		".leaflet-control-locate a.icon-location",
		".leaflet-control-locate a img",
		"a.leaflet-bar-part.leaflet-bar-part-single.icon-spinner.animate-spin",
		"a.leaflet-bar-part.leaflet-bar-part-single.icon-spinner.animate-spin img",
		".leaflet-control-locate a.icon-spinner",
		".leaflet-bar a:only-of-type",
		".leaflet-control-geosearch.active .leaflet-control-geosearch-icon",
		".leaflet-control-geosearch.active .leaflet-control-geosearch-wrap",
		".leaflet-control-geosearch input",
		".leaflet-control-geosearch.active input",
		"input[type=email]:focus,input[type=number]:focus,input[type=password]:focus,input[type=text]:focus,textarea:focus",
		".leaflet-control-geosearch-results",
		".leaflet-control.geosearch.active .leaflet-control-geosearch-results",
		".drawer:after",
		".drawer:before",
		".drawer-close,.drawer-inner dd",
		".drawer-close",
		".show-drawer .drawer",
		".drawer-open span",
		".drawer-buttons>div",
		".drawer-buttons>div:hover",
		".map-search-error .leaflet-control-geosearch,.map-search-error .leaflet-control-geosearch-wrap",
		".map-search-error .leaflet-control-geosearch input",
		".animate-spin .icon-spin-inner",
		".leaflet-touch .leaflet-bar-part-single",
		".leaflet-touch .leaflet-control-locate",
		".maps-user-icon"
	]
}